name: WebAssembly Tests

on: [push, pull_request]

jobs:
  wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-pack
      - run: wasm-pack test --node